# Generated by Django 3.1 on 2020-09-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200920_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sort_by',
            field=models.CharField(choices=[('E', 'Equipment'), ('C', 'Category')], default='E', max_length=1),
        ),
    ]
