# Generated by Django 3.1 on 2020-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200923_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='measurement',
        ),
        migrations.AddField(
            model_name='user',
            name='Measurement',
            field=models.CharField(choices=[('M', 'Metric'), ('I', 'Imperial')], default='M', max_length=1),
        ),
    ]
