# Generated by Django 3.1 on 2020-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercise_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('equip_category', models.CharField(choices=[('BW', 'Bodyweight'), ('WE', 'Weights'), ('HE', 'Household Equipment'), ('SE', 'Misc. Equipment')], default='BW', max_length=2)),
                ('category', models.CharField(choices=[('CH', 'Chest'), ('B', 'Back'), ('AR', 'Arms'), ('CO', 'Core'), ('L', 'Legs'), ('ST', 'Stamina'), ('AG', 'Agility'), ('SP', 'Speed')], default='CH', max_length=2)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
