# Generated by Django 3.1 on 2020-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise_item',
            old_name='equip_category',
            new_name='equipment_category',
        ),
        migrations.RenameField(
            model_name='exercise_item',
            old_name='category',
            new_name='primary_focus',
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='secondary_focus',
            field=models.CharField(choices=[('CH', 'Chest'), ('B', 'Back'), ('AR', 'Arms'), ('CO', 'Core'), ('L', 'Legs'), ('ST', 'Stamina'), ('AG', 'Agility'), ('SP', 'Speed')], default='CH', max_length=2),
        ),
    ]
