# Generated by Django 3.1 on 2020-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200924_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_item',
            name='primary_focus',
            field=models.CharField(choices=[('CH', 'Chest'), ('B', 'Back'), ('AR', 'Arms'), ('CO', 'Core'), ('L', 'Legs'), ('ST', 'Stamina'), ('AG', 'Agility'), ('SP', 'Speed'), ('NO', '------')], default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercise_item',
            name='secondary_focus',
            field=models.CharField(choices=[('CH', 'Chest'), ('B', 'Back'), ('AR', 'Arms'), ('CO', 'Core'), ('L', 'Legs'), ('ST', 'Stamina'), ('AG', 'Agility'), ('SP', 'Speed'), ('NO', '------')], default='NO', max_length=2),
        ),
    ]
