# Generated by Django 3.1 on 2020-09-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200924_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_item',
            name='level_1',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_10',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_2',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_3',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_4',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_5',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_6',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_7',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_8',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='level_9',
            field=models.CharField(default='6 reps', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='tooltip_illustration',
            field=models.FilePathField(default='arms.png', path='main\\static\\main\\images'),
        ),
    ]
