# Generated by Django 3.1 on 2020-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200924_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_item',
            name='friend_verified',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='video_verified',
            field=models.BooleanField(default='False'),
        ),
    ]
