# Generated by Django 3.1 on 2020-09-29 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200929_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
