# Generated by Django 3.1 on 2020-10-04 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_exercise_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_item',
            name='tooltip_illustration',
            field=models.FilePathField(default='missing.gif', path='/main/images/tooltip illustrations'),
        ),
        migrations.CreateModel(
            name='UserExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise_item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise_item',
            name='users',
            field=models.ManyToManyField(through='main.UserExercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
