# Generated by Django 3.1 on 2020-10-10 18:38

from django.db import migrations
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201010_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_item',
            name='tooltip_illustration',
            field=relativefilepathfield.fields.RelativeFilePathField(default='missing.gif', path='/main/static/main/images/tooltip illustrations/'),
        ),
    ]
