# Generated by Django 3.1 on 2020-10-10 18:41

from django.db import migrations
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201010_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_item',
            name='tooltip_illustration',
            field=relativefilepathfield.fields.RelativeFilePathField(default='missing.gif', path='/static/main/images/tooltip illustrations'),
        ),
    ]
