# Generated by Django 3.1 on 2020-10-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201010_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_item',
            name='tooltip_illustration',
            field=models.FilePathField(default='missing.gif', path='/static/main/images/tooltip illustrations/'),
        ),
    ]
